# Generated by Django 4.1.3 on 2024-07-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_rename_center_code_tp_center_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tp',
            name='Email_office',
            field=models.EmailField(default='ty', max_length=254),
            preserve_default=False,
        ),
    ]
