# Generated by Django 4.1.3 on 2024-07-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_tp_email_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tp',
            name='Email_office',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
