# Generated by Django 4.1.3 on 2024-07-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_tp_email_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tp',
            name='Batch_Code',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='tp',
            name='Code_of_the_training_Partner',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='tp',
            name='Father_Name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='tp',
            name='Mother_Name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='tp',
            name='Name_of_the_Candidate',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='tp',
            name='Name_of_the_training_Partner',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='tp',
            name='Practical1',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='tp',
            name='Practical2',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='tp',
            name='Project',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='tp',
            name='Roll_No',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
