# Generated by Django 4.1.3 on 2024-07-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubmission',
            name='submission_date',
            field=models.DateTimeField(null=True),
        ),
    ]
